language: node_js
node_js:
  - "stable"
script:
  - CI=false npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  keep_history: true
  target-branch: gh-pages
  on:
    branch: main