export const MenuItems = [
	{text: 'About',
	path:'/about',
	cName: 'navbar-link',
  url: '#about'},
	{text: 'Experience',
	path:'/experience',
	cName: 'navbar-link',
  url: '#experience'},
	{text: 'Publications',
	path:'/publications',
	cName: 'navbar-link',
  url: '#publications'},
	{text: 'Blog',
	path:'/blog',
	cName: 'navbar-link',
  url: '#blog'},
	{text: 'Contact',
	path:'/contact',
	cName: 'navbar-link',
  url: '#contact'},
	{text: 'Resume',
	path:'/resume',
	cName: 'navbar-mobile-link',
  url: '#resume'}
]
