export const MenuItems = [
	{text: 'About',
	path:'/about',
	cName: 'navbar-link',
  url: '#'},
	{text: 'Experience',
	path:'/experience',
	cName: 'navbar-link',
  url: '#'},
	{text: 'Achievements',
	path:'/achievments',
	cName: 'navbar-link',
  url: '#'},
	{text: 'Publications',
	path:'/publications',
	cName: 'navbar-link',
  url: '#'},
	{text: 'Blog',
	path:'/blog',
	cName: 'navbar-link',
  url: '#'},
	{text: 'Contact',
	path:'/contact',
	cName: 'navbar-link',
  url: '#'},
	{text: 'Resume',
	path:'/resume',
	cName: 'navbar-mobile-link',
  url: '#'}
]
